spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false 
  mvc:  
    pathmatch: #swagger위한설정 
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    org:
      hibernate: 
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndTripleDES
    property:
      prefix: ENC(
      sufix: )
